Author/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.conf.urls.static import static
from app.forms import PasswordChange, PasswordResetFormView, MySetPasswordForm
from django.contrib.auth import views as auth_views
from app.views import ResetPasswordView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('register/', views.Register, name='register'),
    path('signin/', views.Sign_in, name='signin'),
    path('base/', views.base, name='base'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('buyer/', views.buyer, name='buyer'),
    path('seller/', views.seller, name='seller'),
    path('profile/', views.profile, name='profile'),
    path('showbook/', views.showbook, name='showbook'),
    path('logout/', views.user_logout, name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    # password reset urls
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),

] 
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from .models import Buyer
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, PasswordResetForm, SetPasswordForm, AuthenticationForm, UsernameField
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _
from .models import CustomModel


class BuyerForm(forms.ModelForm):
    class Meta:
        bookname = forms.CharField(label='Book Name : ', max_length=100)
        price = forms.IntegerField(label='Price : ')
        image = forms.CharField(label='Upload Image : ')
        model = Buyer
        fields = ('bookname','price','image')


class PasswordChange(PasswordChangeForm):
        old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "autofocus": True , 'class':'form-control'}
        ),
    )
        new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class':'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
        new_password2 = forms.CharField(
            label=_("New password confirmation"),
            strip=False,
            widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class':'form-control'}),
        )

class PasswordResetFormView(PasswordResetForm):
        email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", 'class':'form-control'}),
    )
        

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class':'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password",'class':'form-control'})
    )
        
# class ProfileForm(forms.ModelForm):
#     def clean_email(self):
#         email = self.cleaned_data.get("email")
#         if CustomUser.objects.filter(email=email).exists():
#             raise forms.ValidationError("Email already exists")
#         return email
#     class Meta:
#         model = Customer
#         fields = ['Name','city','state','zipcode','locality']
#         widgets = {
#             'Name':forms.TextInput(attrs={'class':'form-control'}),
#             'city':forms.TextInput(attrs={'class':'form-control'}),
#             'state':forms.Select(attrs={'class':'form-control'}),
#             'zipcode':forms.NumberInput(attrs={'class':'form-control'}),
#             'locality':forms.TextInput(attrs={'class':'form-control'}),
#             # 'address2':forms.TextInput(attrs={'class':'form-control'}),

#                   }
        

templates/base.html
{% load static %}
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Chary &middot; Wary</title>
<meta http-equiv="content-language" content="en-us" />
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta name="author" content="Sadhana Ganapathiraju" />
<meta name="description" content="Chary . Wary is a simply stunning template for a blog." />
<meta name="keywords" content="chary,wary,xhtml,css,free templates,templates,simplygold,sadhana,sadhana ganapathiraju" />
<link rel="start" title="SimplyGold" href="#" />


<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="{% static 'css/ie-win.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}

{% block header %}
<div id="header">
</div>
<div id="navigation">
  <ul>

    {% if request.user.is_authenticated %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'about' %}">About</a></li>
    <li><a href="{% url 'contact' %}">contact</a></li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
    <li><a href="{% url 'profile' %}">Your Profile</a></li>
    <li class="active"><a href="">Hello! {{ request.user.email }}</a></li>
    {% else %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'signin' %}">Sign in</a></li>
    <li><a href="{% url 'register' %}">Register</a></li>
    {% endif %}
  </ul>
</div><br>
{% endblock %}

{% block navbar %}

{% endblock %}

{% block home %}
{% endblock %}

{% block body %}
{% endblock %}

templates/buyer.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="{% static 'css/ie-win.css' %}">
<style>

</style>
</head>
<body>
  {% block body %}
  <div class="container">
    <div class="box" >
      <form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Add Book Here!!</h3>
        <label for="bookname">Book Name : </label>
        <input type="text" name="bookname" id="" required class="form-control"><br>
        <label for="bookprice">Book price : </label>
        <input type="number" name="bookprice" id="" class="form-control"><br>
        <input type="file" name="myimage" id="" required><br><br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form> 
    </div><br>
              <div >
            <a href="{% url 'showbook' %}" class="btn btn-success text-light">Go To Your Book</a><br><br>
          </div>
  </div>

          <!-- my_template.html -->
          {% if messages %}
          <div class="container mt-3">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          </div>
        {% endif %}
  <!-- Footer  -->
  <div id="footer">
    <div id="copyright"> Design copyright &copy; 2006 <a href="http://www.nikhedonia.com/" title="SimplyGold">Sadhana Ganapathiraju</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
  </div>
  {% endblock %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block home %}
    <div class="outer-di">
        <h1 class="text-center">Contact Us</h1>
        <div class="inner-di">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Name" class="form-control w-40"><br>
                <input type="email" name="email" placeholder="Email" class="form-control w-40" required><br>
                <input type="text" name="address" placeholder="Address" class="form-control w-40"><br>
                <textarea name="message" id="" cols="30" rows="10" placeholder="Message" class="form-control w-40" required></textarea><br>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
    <div id="footer">

        <div id="copyright"> Design copyright &copy; 2024 <a href="http://www.nikhedonia.com/" title="SimplyGold">Abdur Rahman</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
      </div>
    {% endblock %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    {% block home %}
    <div class="container">
        <div class="box">
            <h3>Welcome in Book Seler & Buyer Shop.</h3><br>
            <div id="col1">
                <h2>You are buyer</h2>
                <p>Click this link bellow!</p><br>
                <a href="{% url 'buyer' %}" class="buttons">Buyer</a>
            </div>
            <div id="col2">
                <h2>You are Seler</h2>
                <p>Click this link bellow!</p><br>
                <a href="{% url 'seller' %}" class="buttons">Seler</a>
            </div>
        </div>
 
    </div>
    {% endblock %}
</body>
</html>

templates/password_reset.html
{% extends "base.html" %}
{% block body %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'signin' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock %}

templates/password_reset_complete.html
{% extends "base.html" %}
{% block home %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and 
                        <a href="{% url 'signin' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block home %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="outer-di">
    <h1 class="text-center">Your Profile!</h1>
    <div class="inner-di">
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="firstname" placeholder="firstname" class="form-control w-40"><br>
            <input type="text" name="lastname" placeholder="lastname" class="form-control w-40"><br>
            <input type="password" name="password" placeholder="Password" class="form-control w-40"><br>
            <input type="email" name="email" placeholder="Email" class="form-control w-40" required><br>
            <input type="text" name="phone" placeholder="Phone" class="form-control w-40"><br>
            <textarea name="message" id="" cols="30" rows="10" placeholder="Message" class="form-control w-40" required></textarea><br>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>
<div id="footer">

    <div id="copyright"> Design copyright &copy; 2024 <a href="http://www.nikhedonia.com/" title="SimplyGold">Abdur Rahman</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
  </div>
{% endblock %}

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="outer-div">
    <div class="inner-div">
      <div class="form-container">
        <h4 class="title">Create account</h4>
        <p class="sub-title">Let's get statred with your 30 days free trial</p>
        <form class="form" action="" method="post">
            {% csrf_token %}
          <input type="text" class="input" placeholder="First name" name="first_name">
          <input type="text" class="input" placeholder="Last name" name="last_name">
          <input type="email" class="input" placeholder="Email" name="email" required>
          <input type="password" class="input" placeholder="Password" name="password" required>
          <input type="text" name="phonenumber" id="" placeholder="Phone number" class="input" maxlength="15" required>
          <button class="form-btn" type="submit" >Create account</button>
        </form>
        <p class="sign-up-label">
          Already have an account?<span class="sign-up-link">
            <a class="link" href="{% url 'signin' %}">Login here</a></span>
        </p>
        <div class="buttons-container">

          <div class="google-login-button">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.1" x="0px" y="0px" class="google-icon" viewBox="0 0 48 48" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12
      c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24
      c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path>
              <path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657
      C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path>
              <path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36
      c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path>
              <path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571
      c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
            </svg>
            <span>  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
            </span>
          </div>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <small {% if message.tags %} class="{{ message.tags }} text-danger"{% endif %}>{{ message }}</small>
              {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</body>
</html>

templates/seller.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="{% static 'css/ie-win.css' %}">
</head>
<body>
  {% block body %}
  <div id="content-wrapper">
    <div id="content">
    {% if products %}
    {% for product in products %}
    <div id="content">
      <p><a href="#" class="drop-shadow"><img src="{{ product.image.url }}" width="100" height="150" alt="The Mephisto Club by Tess Gerritsen" class="captionated" /></a></p>
      <hr />
    </div>
    {% endfor %}
    {% else %}
    <p>No book Available!</p>
    {% endif %}
      <hr />
    </div>
  </div>
  <div id="footer">

    <div id="copyright"> Design copyright &copy; 2006 <a href="http://www.nikhedonia.com/" title="SimplyGold">Sadhana Ganapathiraju</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
  </div>


  {% endblock %}



</body>
</html>

templates/showbook.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="{% static 'css/ie-win.css' %}">
<style>

</style>
</head>
<body>

  {% block body %}

  <div id="content-wrapper">
    <div id="content">
    {% if products %}
      {% for product in products %}
          <div id="content">
              <p>
                {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.bookname }}" style="border: 1px solid black;">
                {% endif %}
              <hr/>
              </p>
          </div>
      {% endfor %}
    {% else %}
    <p>No book Available!</p><br>
    <a href="{% url 'buyer' %}" class="btn btn-danger text-light">Add Book</a>
  {% endif %}
      <hr />
    </div>
  </div>
      <!-- my_template.html -->
      {% if messages %}
        <div class="container mt-3">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>
      {% endif %}

  <!-- Footer  -->
  <div id="footer">
    <div id="copyright"> Design copyright &copy; 2006 <a href="http://www.nikhedonia.com/" title="SimplyGold">Sadhana Ganapathiraju</a> | <a href="#showcase/free_templates/" title="More Free Templates">Free Templates</a> | <a href="#showcase/commercial_templates/" title="More Commercial Templates">Commercial Templates</a> | <a href="http://validator.w3.org/check/referer" title="Xhtml 1.1 Strict">Xhtml Happy</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Css 2.0 Strict">Css Happy</a> </div>
  </div>
  {% endblock %}
</body>
</html>

templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  <div class="outer-div">
    <div class="inner-div">
      <div class="form-container">
        <h4 class="title">Sign in</h4>
        <form class="form" method="post"> 
            {% csrf_token %}
          <input type="email" class="input" placeholder="Email" name="email" required>
          <input type="password" class="input" placeholder="Password" name="password">
          <p class="page-link">
            <!-- <span class="page-link-label">Forgot Password?</span> -->
            <p><a href="{% url 'password_reset' %}">Forget Password?</a></p>
          </p>
          <button class="form-btn" type="submit">Log in</button>
        </form>
        <p class="sign-up-label">
          Don't have an account?<span class="sign-up-link">
            <a href="{% url 'register' %}">Register here</a>
          </span>
        </p>
        <div class="buttons-container">
          <div class="google-login-button">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.1" x="0px" y="0px" class="google-icon" viewBox="0 0 48 48" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
              <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12
      c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24
      c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path>
              <path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657
      C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path>
              <path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36
      c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path>
              <path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571
      c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
            </svg>
            <span>  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>


              
            </span>
          </div>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <small {% if message.tags %} class="{{ message.tags }} text-danger"{% endif %}>
                  {{ message }}</small>
              {% endfor %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </div>




</body>
</html>